name: ci-sonarcloud-scan

on:
  workflow_call:
    secrets:
      grid_github_token:
        required: true
      grid_sonar_token:
        required: true

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache unit-test artefacts
        uses: actions/cache@v2
        with:
          path: unit-test-artefacts
          key: unit-test-artefacts-${{ github.run_number }}
      - run: |
          cat unit-test-artefacts/coverage.json | sed -e "s;/app/app/;/app/;g" | tee coverage.json
          cat unit-test-artefacts/.resultset.json | sed -e "s;/app/app/;/app/;g" | tee .resultset.json
          cp unit-test-artefacts/.resultset.json .resultset.json
          cp unit-test-artefacts/coverage.json coverage.json
          cp unit-test-artefacts/results.xml results.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.grid_github_token }}
          SONAR_TOKEN: ${{ secrets.grid_sonar_token }}
