name: feature-test-pack-workflow

on:
  workflow_call:
    inputs:
      watchman_repo:
        type: string
        required: true
        description: watchman repository follwing the format - {org}/{repo}
      env:
        type: string
        required: true
        description: environment. eg. dev|uat|pre-prod|prod
      aws_region:
        type: string
        required: true
        description: aws region
      s3_bucket_reports:
        type: string
        required: true
        description: aws bucket where the test reports will be exported
      test_packs:
        type: string
        required: true
        description: comma separated test packs. eg. olaf_features,wishlist_features
      browser:
        type: string
        required: false
        default: chrome
    secrets:
      grid_git_grid_token:
        required: true
      aws_role:
        required: true

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      test-pack-json: ${{ steps.set-vars.outputs.test-pack-json }}
    steps:
      - id: set-vars
        name: set output
        run: |
          test_pack_json=$(echo ${{ inputs.test_packs }} | jq -cR '. | split(",")')
          echo test_pack_json - ${test_pack_json}
          echo "::set-output name=test-pack-json::$test_pack_json"
  run-test-pack:
    needs: [set-vars]
    runs-on: ubuntu-latest
    continue-on-error: true
    # These permissions are required to use Github OIDC.
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        test_pack: ${{ fromJson(needs.set-vars.outputs.test-pack-json) }}
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: '101.0.4951.41'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: ${{ secrets.aws_role }}
      - name: clone watchman repo
        run: |
          # checkout watchman repo using git
          git clone https://${{ secrets.grid_git_grid_token }}@github.com/${{ inputs.watchman_repo }}.git 
      - name: install dependencies
        run: |
          cd watchman/features
          BUNDLE_GEMFILE="${{ github.workspace }}/watchman/Gemfile"
          bundle install
      - name: run tests
        run: |
          echo "running test - ${{ matrix.test_pack }}"
          
          cd watchman
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          
          date_now="$(date +%F)"
          report_file_name="${{ matrix.test_pack }}.html"

          bundle exec cucumber ./features/${{ matrix.test_pack }} ENVIRONMENT=${{ inputs.env }} BROWSER=${{ inputs.browser }} --format html --out=${report_file_name} -f pretty || cucumber_exit_code="$?"
          
          aws s3 cp --acl public-read ${report_file_name} s3://${{ inputs.s3_bucket_reports }}/${{ inputs.env }}/${date_now}/${report_file_name}

          if [[ "$cucumber_exit_code" != "0" ]]; then
            exit 1
          fi
  
