name: tag-test-pack-workflow
on:
  workflow_dispatch:
    inputs:
      env:
        type: string
        required: true
      test-pack-tag:
        type: string
        required: true
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo hello world
